services:
  app:
    build: .
    ports:
      - "9092:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - CI_ENVIRONMENT=development
