services:
  app:
    build: .
    ports:
    - "9092:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    environment:
      - CI_ENVIRONMENT=development
    depends_on:
      - tailwind

  tailwind:
    build: .
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: tailwindcss -i public/assets/css/input.css -o public/assets/css/app.css --watch=always
